// GENERATED by tau-sdk-codegen. Do not edit by hand.
export interface Model { backend: string; model: string }
export interface ToolConfig { native: string; description?: string }
export interface AgentConfig { display_name: string; package: string; model: string }

export const models = (m: Record<string, Model>): Record<string, Model> => m;
export const tool = (c: ToolConfig): ToolConfig => c;
export const agent = (c: AgentConfig): AgentConfig => c;
