// GENERATED by tau-sdk-codegen. Do not edit by hand.
export interface Model { backend: string; model: string }
export interface Capability { kind: string; paths?: string[] }
export interface ToolConfig { native: string; description?: string; capabilities?: Capability[] }
export interface Prompt { system: string }
export interface AgentConfig {
  display_name: string;
  package: string;
  model: string;
  prompt?: Prompt;
  tools?: Record<string, ToolConfig>;
}

export const models = (m: Record<string, Model>): Record<string, Model> => m;
export const tool = (c: ToolConfig): ToolConfig => c;
export const agent = (c: AgentConfig): AgentConfig => c;
