// GENERATED by `tau dev` — DO NOT EDIT.        (VISION FIXTURE — target state)
// tau:gen registry-hash=sha256:4f2c81d09aa3   ← stamped against the project
// registry; a stale stamp is a LOUD build error (the anti-Prisma rule,
// E-1.4; worked-examples B6, invariant 4).
//
// Typed bindings for everything the vocabulary declares. This file is the
// bridge that makes the choreography type-check against the constitution.

export interface TicketIn {
  ticket: { subject: string; body: string; customer_id: string; source?: string };
}

export interface TriageVerdict {
  category: "billing" | "bug" | "howto" | "abuse";
  urgency: 1 | 2 | 3 | 4;
  billing_flag: boolean;
  customer_id: string;
}

export declare const agents: {
  /** agents/triage.md — model: default; tools: kb.search, billing.lookup */
  triage: AgentRef<TicketIn["ticket"], TriageVerdict>;
};

export declare const tools: {
  kb: { search: ToolRef<{ query: string }, { hits: string[] }> };
  /** #[tau::tool] billing_lookup — caps: net billing.corp.internal:443 */
  billing: { lookup: ToolRef<{ customer: string }, { standing: string }> };
};

// Handle machinery (runtime projection) — emitted by the typed client
// generator; shown here only so the fixture reads whole.
export declare interface AgentRef<I, O> { readonly __agent: [I, O] }
export declare interface ToolRef<I, O> { readonly __tool: [I, O] }
