// GENERATED by `tau dev` — DO NOT EDIT.        (VISION FIXTURE — target state)
// tau:gen registry-hash=sha256:2ce6f00b8d41
// Typed bindings projected from the vocabulary — including HOST tools,
// whose types come from schemas/host/*.json. To the choreography they are
// indistinguishable from native tools; the difference lives on the card.

export interface AlertRef { id: string }
export interface RunbookRef { runbook_id: string; incident_id: string }
export interface Findings { cause: string; evidence: object[]; confidence: string }
export interface Applied { status: "applied" | "refused"; log?: string }

export declare const agents: {
  investigator: AgentRef<AlertRef, Findings>;
  runbookExecutor: AgentRef<RunbookRef, Applied>;
};

export declare const tools: {
  metrics: { query: ToolRef<{ query: string; range: string }, { series: object[] }> };
  pager: { ack: ToolRef<{ incident_id: string }, { acked: boolean }> };
  runbook: { apply: ToolRef<{ plan: object }, { status: string; log?: string }> };
};

export declare interface AgentRef<I, O> { readonly __agent: [I, O] }
export declare interface ToolRef<I, O> { readonly __tool: [I, O] }
