//! `embed_c` — render the C HOST glue that loads + drives the EPIC 5.1
//! wasm-guest component via the wasmtime C API.
//!
//! The four `tau:host/host` imports (wit/tau-host.wit) are a frozen contract,
//! so the header declares them directly; the cap-derived WASI imports in the
//! generated world are satisfied by `wasmtime_wasi` and need no host bodies.
//! Bodies are `TODO(EPIC 7.1)` stubs. Pure string renderer — no tool runs at
//! emit time. The embedded `tau.wit` lets a product regenerate typed bindings
//! with `wit-bindgen` / the wasmtime C API if it wants more than this stub.

use std::collections::BTreeMap;
use std::path::PathBuf;

/// Inputs for [`render_embed_c`].
pub struct EmbedCInput<'a> {
    /// Sanitized project stem: uppercased for the include guard, lowercased in
    /// docs/prose. File names are fixed (`tau_embed.{h,c}`).
    pub base_name: &'a str,
    /// Lowercase-hex IR module hash (README provenance).
    pub ir_hash: &'a str,
    /// Cap-derived WIT world text, embedded verbatim.
    pub wit: &'a str,
}

/// Render the C host scaffold as relative-path -> contents under `embed-c/`.
pub fn render_embed_c(input: EmbedCInput) -> BTreeMap<PathBuf, String> {
    let mut out = BTreeMap::new();
    let guard = format!(
        "TAU_EMBED_{}_H",
        input
            .base_name
            .chars()
            .map(|c| if c.is_ascii_alphanumeric() { c.to_ascii_uppercase() } else { '_' })
            .collect::<String>()
    );

    out.insert(
        PathBuf::from("embed-c/tau_embed.h"),
        format!(
            r#"/* Generated by `tau embed --host c` (EPIC 5.2) — do not edit. */
#ifndef {guard}
#define {guard}

#include <stdint.h>

/* The four `tau:host/host` imports (wit/tau-host.wit) the guest requires.
 * Wire these to your product in tau_embed.c (EPIC 7.1). `request_json` /
 * `event_json` are NUL-terminated serialized JSON; returned strings are
 * heap-allocated and owned by the caller. */
char    *tau_host_complete(const char *request_json);   /* -> CompletionResponse JSON */
uint64_t tau_host_now_millis(void);
uint64_t tau_host_next_u64(void);
void     tau_host_emit_event(const char *event_json);

/* Load the bundled wasm-guest component, wire the imports above, and drive its
 * `run(prompt)` export. Returns 0 on success. RunEvents stream through
 * tau_host_emit_event. `component_path` is the `.wasm` from `tau build
 * --target wasm-guest`. */
int tau_embed_run(const char *component_path, const char *prompt);

#endif /* {guard} */
"#,
        ),
    );

    out.insert(
        PathBuf::from("embed-c/tau_embed.c"),
        r#"/* Generated by `tau embed --host c` (EPIC 5.2) — a scaffold.
 *
 * Drives a tau wasm-guest component through the wasmtime C API. The host-import
 * bodies and the instantiate/call wiring are TODO(EPIC 7.1) stubs: this file
 * compiles the shape of the glue, not a working runtime. Link against
 * libwasmtime and fill the TODOs. */
#include "tau_embed.h"

#include <stdlib.h>
#include <string.h>

/* wasmtime C API — provided by libwasmtime (https://docs.wasmtime.dev/c-api). */
#include <wasmtime.h>

char *tau_host_complete(const char *request_json) {
    (void)request_json;
    /* TODO(EPIC 7.1): bridge to an LLM backend; return CompletionResponse JSON. */
    return NULL;
}

uint64_t tau_host_now_millis(void) {
    /* TODO(EPIC 7.1): return a wall-clock millisecond count. */
    return 0;
}

uint64_t tau_host_next_u64(void) {
    /* TODO(EPIC 7.1): return the next u64 from your RandomSource. */
    return 0;
}

void tau_host_emit_event(const char *event_json) {
    (void)event_json;
    /* TODO(EPIC 7.1): consume the streamed RunEvent JSON. */
}

int tau_embed_run(const char *component_path, const char *prompt) {
    (void)component_path;
    (void)prompt;
    /* TODO(EPIC 7.1): with the wasmtime C API —
     *   1. wasm_engine_new / wasmtime_store_new (+ wasmtime_wasi for the WASI
     *      imports listed in tau.wit),
     *   2. wasmtime_component_from_file(component_path),
     *   3. wasmtime_component_linker_define the four tau:host/host imports to
     *      the tau_host_* functions above,
     *   4. instantiate and call the `run(prompt)` export.
     * See tau.wit for the exact import/export set. */
    return -1;
}
"#
        .to_string(),
    );

    out.insert(PathBuf::from("embed-c/tau.wit"), input.wit.to_string());

    out.insert(
        PathBuf::from("embed-c/README.md"),
        format!(
            "# tau embed --host c ({base} host scaffold)\n\n\
             Generated by `tau embed --host c` (EPIC 5.2). Baked IR hash: \
             `{hash}`.\n\n\
             C host glue that loads a `tau build --target wasm-guest` component \
             through the [wasmtime C API](https://docs.wasmtime.dev/c-api) and \
             drives its `run(prompt)` export. `tau_embed.h` declares the four \
             frozen `tau:host/host` imports plus `tau_embed_run`; fill in the \
             `TODO(EPIC 7.1)` bodies in `tau_embed.c` and link `libwasmtime`.\n\n\
             `tau.wit` is the component's WIT world, embedded for reference. To \
             regenerate typed bindings instead of hand-writing them, run \
             `wit-bindgen c tau.wit` (guest side) or use the wasmtime C API's \
             component bindings (host side).\n",
            base = input.base_name,
            hash = input.ir_hash,
        ),
    );

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_embed_c_emits_wasmtime_host_stub_with_wit_imports() {
        let wit = "package tau:generated@0.1.0;\n\nworld runner {\n    \
            import tau:host/host@0.1.0;\n    export run: func(prompt: string) \
            -> result<string, string>;\n}\n";
        let out = render_embed_c(EmbedCInput { base_name: "trivial", ir_hash: "abc123", wit });

        for f in ["tau_embed.h", "tau_embed.c", "tau.wit", "README.md"] {
            assert!(out.contains_key(&PathBuf::from(format!("embed-c/{f}"))), "missing {f}");
        }

        let h = &out[&PathBuf::from("embed-c/tau_embed.h")];
        // Include guard from base_name; the four frozen tau:host/host imports.
        assert!(h.contains("#ifndef TAU_EMBED_TRIVIAL_H"), "{h}");
        for sym in ["tau_host_complete", "tau_host_now_millis", "tau_host_next_u64", "tau_host_emit_event"] {
            assert!(h.contains(sym), "header missing {sym}");
        }
        assert!(h.contains("tau_embed_run"), "{h}");

        let c = &out[&PathBuf::from("embed-c/tau_embed.c")];
        assert!(c.contains("#include \"tau_embed.h\""), "{c}");
        assert!(c.contains("wasmtime"), "must use the wasmtime C API: {c}");
        assert!(c.contains("/* TODO(EPIC 7.1)"), "port bodies must be TODO stubs: {c}");

        assert_eq!(out[&PathBuf::from("embed-c/tau.wit")], wit);
        assert!(out[&PathBuf::from("embed-c/README.md")].contains("wit-bindgen"));
    }
}
