//! `embed_rust` — render the native HOST crate that drives the EPIC 5.1
//! rust-lib (Variant B) artifact.
//!
//! Sibling to `emit_rust_lib` (which emits the *library* crate baking the IR).
//! This emits the *host* crate that links that library, supplies port impls,
//! and drives `run_ir_streaming`. Since EPIC 7.1 the scaffold is RUNNABLE
//! offline: scaffold-grade ports (echo LLM, xorshift entropy) that a product
//! replaces with its own. Pure string renderer — compiled end-to-end by the
//! `embed_rust_e2e` test in tau-cli.

use std::collections::BTreeMap;
use std::path::PathBuf;

use crate::emit_rust_lib::TauDep;

/// Inputs for [`render_embed_rust`].
pub struct EmbedRustInput<'a> {
    /// Sanitized project stem used as the host crate name.
    pub crate_name: &'a str,
    /// Name of the EPIC 5.1 rust-lib crate this host links (path dep `..`).
    pub lib_crate_name: &'a str,
    /// Lowercase-hex IR module hash (README provenance).
    pub ir_hash: &'a str,
    /// Cap-derived WIT world text, embedded verbatim for reference.
    pub wit: &'a str,
    /// How the generated crate depends on `tau-runtime-core` / `tau-ir`.
    pub tau_dep: TauDep<'a>,
}

/// Render the rust HOST scaffold as crate-relative-path -> contents under
/// `embed-rust/`. A product drops this beside the rust-lib crate, replaces
/// the scaffold port bodies (echo LLM, reject-all tools, xorshift entropy)
/// with its own, and runs it to drive the workflow.
pub fn render_embed_rust(input: EmbedRustInput) -> BTreeMap<PathBuf, String> {
    let mut out = BTreeMap::new();

    out.insert(
        PathBuf::from("embed-rust/Cargo.toml"),
        format!(
            r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"
publish = false

# Generated by `tau embed --host rust` (EPIC 5.2/7.1). Native host scaffold:
# links the sibling rust-lib crate, supplies scaffold port impls, drives
# run_ir_streaming. Replace the Echo/XorShift ports with your product's.
[dependencies]
{lib} = {{ path = ".." }}
tau-runtime-core = {core_dep}
tau-ir = {ir_dep}
serde_json = {{ version = "1" }}
futures = {{ version = "0.3" }}
"#,
            name = input.crate_name,
            lib = input.lib_crate_name,
            core_dep = input
                .tau_dep
                .dep_table("tau-runtime-core", r#"features = ["wasm-interpreter"]"#),
            ir_dep = input.tau_dep.dep_table("tau-ir", ""),
        ),
    );

    out.insert(
        PathBuf::from("embed-rust/src/main.rs"),
        format!(
            r#"//! Generated by `tau embed --host rust` (EPIC 5.2/7.1) — a runnable scaffold.
//!
//! Links the rust-lib crate (`{lib}`), decodes its baked `TAU_IR`, resolves
//! the entry agent (sole-agent contract — `IrModule::entry_agent`), and
//! drives `run_ir_streaming`, printing each `RunEvent` as a JSON line.
//!
//! The port impls below are scaffold-grade so `cargo run` works offline:
//! - `EchoBackend` — canned completion; REPLACE with your product's LLM client.
//! - `ScaffoldDispatcher::invoke` — rejects every tool; REPLACE with your tools.
//! - `SystemClock` / `XorShiftRandom` — std wall clock + NON-cryptographic
//!   entropy; REPLACE if your product needs real entropy.
//!
//! Capabilities the dispatcher must service are the WIT imports in `tau.wit`.

use std::future::Future;
use std::pin::Pin;
use std::sync::atomic::{{AtomicU64, Ordering}};
use std::sync::Arc;
use std::time::{{SystemTime, UNIX_EPOCH}};

use futures::StreamExt;
use serde_json::Value;
use tau_ir::ToolId;
use tau_runtime_core::embed::{{
    batch_to_stream, run_ir_streaming, Clock, CompletionRequest, CompletionResponse,
    CompletionStream, DynLlmBackend, LlmBackend, LlmError, RandomSource, RuntimeError,
    StopReason, ToolDispatcher, ToolInvocationResult,
}};
use {lib}::TAU_IR;

/// Scaffold inference: every backend name resolves to this canned echo.
struct EchoBackend;

impl LlmBackend for EchoBackend {{
    fn name(&self) -> &str {{
        "embed-scaffold-echo"
    }}

    async fn complete(&self, _req: CompletionRequest) -> Result<CompletionResponse, LlmError> {{
        Ok(CompletionResponse::new(
            "embed-rust scaffold reply".to_string(),
            Vec::new(),
            StopReason::EndTurn,
            None,
        ))
    }}

    async fn stream(&self, req: CompletionRequest) -> Result<CompletionStream, LlmError> {{
        // UFCS: the DynLlmBackend blanket impl makes `self.complete(..)` ambiguous.
        Ok(batch_to_stream(LlmBackend::complete(self, req).await?))
    }}
}}

/// Wall clock in ms since the Unix epoch.
struct SystemClock;

impl Clock for SystemClock {{
    fn now(&self) -> i64 {{
        SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_millis() as i64)
            .unwrap_or(0)
    }}
}}

/// xorshift64* seeded from the clock — NOT cryptographic.
struct XorShiftRandom(AtomicU64);

impl RandomSource for XorShiftRandom {{
    fn fill(&self, dest: &mut [u8]) {{
        let mut i = 0;
        while i < dest.len() {{
            let mut x = self.0.load(Ordering::Relaxed);
            x ^= x << 13;
            x ^= x >> 7;
            x ^= x << 17;
            self.0.store(x, Ordering::Relaxed);
            let bytes = x.wrapping_mul(0x2545F4914F6CDD1D).to_le_bytes();
            let take = core::cmp::min(8, dest.len() - i);
            dest[i..i + take].copy_from_slice(&bytes[..take]);
            i += take;
        }}
    }}
}}

/// Product port surface: tools + LLM backend + mandatory clock/random.
struct ScaffoldDispatcher {{
    backend: Arc<EchoBackend>,
    clock: Arc<SystemClock>,
    random: Arc<XorShiftRandom>,
}}

impl ScaffoldDispatcher {{
    fn new() -> Self {{
        let seed = SystemClock.now() as u64 | 1;
        Self {{
            backend: Arc::new(EchoBackend),
            clock: Arc::new(SystemClock),
            random: Arc::new(XorShiftRandom(AtomicU64::new(seed))),
        }}
    }}
}}

impl ToolDispatcher for ScaffoldDispatcher {{
    fn invoke<'a>(
        &'a self,
        tool_id: &'a ToolId,
        _args: &'a Value,
    ) -> Pin<Box<dyn Future<Output = Result<ToolInvocationResult, RuntimeError>> + Send + 'a>>
    {{
        Box::pin(async move {{
            Err(RuntimeError::ToolNotRegistered {{
                tool_name: tool_id.0.clone(),
                registered: Vec::new(),
            }})
        }})
    }}

    fn llm_backend_for(&self, _backend: &str) -> Result<Arc<dyn DynLlmBackend>, RuntimeError> {{
        Ok(self.backend.clone())
    }}

    fn clock(&self) -> Option<Arc<dyn Clock>> {{
        Some(self.clock.clone())
    }}

    fn random(&self) -> Option<Arc<dyn RandomSource>> {{
        Some(self.random.clone())
    }}
}}

fn main() -> Result<(), Box<dyn std::error::Error>> {{
    futures::executor::block_on(async {{
        let module = Arc::new(tau_runtime_core::embed::from_canonical_bytes(TAU_IR)?);
        let entry = module.entry_agent()?.clone();
        let stream =
            run_ir_streaming(module, &entry, Arc::new(ScaffoldDispatcher::new()), Vec::new())
                .await?;
        futures::pin_mut!(stream);
        while let Some(event) = stream.next().await {{
            println!("{{}}", serde_json::to_string(&event).expect("RunEvent serializes"));
        }}
        Ok(())
    }})
}}
"#,
            lib = input.lib_crate_name,
        ),
    );

    out.insert(PathBuf::from("embed-rust/tau.wit"), input.wit.to_string());

    out.insert(
        PathBuf::from("embed-rust/README.md"),
        format!(
            "# {name} (rust host scaffold)\n\n\
             Generated by `tau embed --host rust` (EPIC 5.2/7.1). Baked IR hash: \
             `{hash}`.\n\n\
             Runnable native host for the sibling rust-lib crate (`{lib}`): \
             `cargo run` works offline against scaffold-grade ports (echo LLM, \
             reject-all tools, xorshift entropy) and prints each `RunEvent` as \
             a JSON line. Replace those ports with your product's inference, \
             tools, and entropy. The capabilities your dispatcher must service \
             are the WIT imports in `tau.wit`.\n",
            name = input.crate_name,
            hash = input.ir_hash,
            lib = input.lib_crate_name,
        ),
    );

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn render_embed_rust_emits_runnable_host_crate() {
        let out = render_embed_rust(EmbedRustInput {
            crate_name: "trivial_host",
            lib_crate_name: "trivial",
            ir_hash: "abc123",
            wit:
                "package tau:generated@0.1.0;\nworld runner {\n    import tau:host/host@0.1.0;\n}\n",
            tau_dep: TauDep::Version("0.0.0"),
        });

        for f in ["Cargo.toml", "src/main.rs", "tau.wit", "README.md"] {
            assert!(
                out.contains_key(&PathBuf::from(format!("embed-rust/{f}"))),
                "missing embed-rust/{f}"
            );
        }

        let main = &out[&PathBuf::from("embed-rust/src/main.rs")];
        // Links the 5.1 rust-lib crate and drives the streaming entrypoint
        // through the sole-agent contract.
        assert!(main.contains("use trivial::TAU_IR"), "{main}");
        assert!(
            main.contains("impl ToolDispatcher for ScaffoldDispatcher"),
            "{main}"
        );
        assert!(
            !main.contains("todo!("),
            "scaffold must be runnable, no todo! stubs: {main}"
        );
        assert!(
            main.contains("entry_agent()"),
            "must use the sole-agent contract: {main}"
        );
        assert!(main.contains("run_ir_streaming("), "{main}");

        let cargo = &out[&PathBuf::from("embed-rust/Cargo.toml")];
        assert!(cargo.contains(r#"trivial = { path = ".." }"#), "{cargo}");
        assert!(
            cargo.contains(
                r#"tau-runtime-core = { version = "0.0.0", features = ["wasm-interpreter"] }"#
            ),
            "{cargo}"
        );
        assert!(
            cargo.contains("serde_json"),
            "emitted Cargo.toml must depend on serde_json (main.rs uses serde_json::Value): {cargo}"
        );
        assert!(cargo.contains("futures"), "{cargo}");
        assert!(
            !cargo.contains("tokio"),
            "scaffold no longer needs tokio: {cargo}"
        );

        assert_eq!(
            out[&PathBuf::from("embed-rust/tau.wit")],
            "package tau:generated@0.1.0;\nworld runner {\n    import tau:host/host@0.1.0;\n}\n"
        );
        assert!(out[&PathBuf::from("embed-rust/README.md")].contains("abc123"));
    }

    #[test]
    fn render_embed_rust_path_dep_points_into_workspace() {
        let out = render_embed_rust(EmbedRustInput {
            crate_name: "trivial_host",
            lib_crate_name: "trivial",
            ir_hash: "abc",
            wit: "w",
            tau_dep: TauDep::Path("/tau/checkout"),
        });
        let cargo = &out[&PathBuf::from("embed-rust/Cargo.toml")];
        assert!(
            cargo.contains(
                r#"tau-runtime-core = { path = "/tau/checkout/crates/tau-runtime-core", features = ["wasm-interpreter"] }"#
            ),
            "{cargo}"
        );
        assert!(
            cargo.contains(r#"tau-ir = { path = "/tau/checkout/crates/tau-ir" }"#),
            "{cargo}"
        );
    }
}
