//! `embed_rust` — render the native HOST crate that drives the EPIC 5.1
//! rust-lib (Variant B) artifact.
//!
//! Sibling to `emit_rust_lib` (which emits the *library* crate baking the IR).
//! This emits the *host* crate that links that library, supplies port impls,
//! and calls `run_ir(TAU_IR, …)`. Bodies are `todo!()` stubs: real port impls
//! are the product's job (EPIC 7.1). Pure string renderer — never compiled here.

use std::collections::BTreeMap;
use std::path::PathBuf;

/// Inputs for [`render_embed_rust`].
pub struct EmbedRustInput<'a> {
    /// Sanitized project stem used as the host crate name.
    pub crate_name: &'a str,
    /// Name of the EPIC 5.1 rust-lib crate this host links (path dep `..`).
    pub lib_crate_name: &'a str,
    /// Lowercase-hex IR module hash (README provenance).
    pub ir_hash: &'a str,
    /// Cap-derived WIT world text, embedded verbatim for reference.
    pub wit: &'a str,
    /// Pinned `tau-runtime-core` / `tau-ir` dependency version.
    pub tau_version: &'a str,
}

/// Render the rust HOST scaffold as crate-relative-path -> contents under
/// `embed-rust/`. A product drops this beside the rust-lib crate, fills in the
/// `StubDispatcher` port bodies (EPIC 7.1), and runs it to drive the workflow.
pub fn render_embed_rust(input: EmbedRustInput) -> BTreeMap<PathBuf, String> {
    let mut out = BTreeMap::new();

    out.insert(
        PathBuf::from("embed-rust/Cargo.toml"),
        format!(
            r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"
publish = false

# Generated by `tau embed --host rust` (EPIC 5.2). Native host scaffold: links
# the sibling rust-lib crate, supplies port impls (EPIC 7.1), drives run_ir.
[dependencies]
{lib} = {{ path = ".." }}
tau-runtime-core = {{ version = "{ver}" }}
tau-ir = {{ version = "{ver}" }}
tokio = {{ version = "1", features = ["macros", "rt-multi-thread"] }}
"#,
            name = input.crate_name,
            lib = input.lib_crate_name,
            ver = input.tau_version,
        ),
    );

    out.insert(
        PathBuf::from("embed-rust/src/main.rs"),
        format!(
            r#"//! Generated by `tau embed --host rust` (EPIC 5.2) — a scaffold.
//!
//! Links the rust-lib crate (`{lib}`), decodes its baked `TAU_IR`, and drives
//! `run_ir` with a dispatcher whose port bodies are `todo!()` stubs. Fill them
//! in (EPIC 7.1) to bridge tools + inference to your product, then run.
//!
//! Capabilities the dispatcher must service are the WIT imports in `tau.wit`.

use std::sync::Arc;

use tau_ir::{{from_canonical_bytes, ToolId}};
use serde_json::Value;
use tau_runtime_core::builder::DynLlmBackend;
use tau_runtime_core::error::RuntimeError;
use tau_runtime_core::interpreter::tool_dispatch::{{ToolDispatcher, ToolInvocationResult}};
use {lib}::{{run_ir, TAU_IR}};

/// Product port surface. Every method is a `todo!()` stub — EPIC 7.1 supplies
/// the real bodies (tool execution + LLM backend resolution). The default trait
/// methods (clock/random/assets/…) are inherited; override as your host needs.
struct StubDispatcher;

impl ToolDispatcher for StubDispatcher {{
    fn invoke<'a>(
        &'a self,
        _tool_id: &'a ToolId,
        _args: &'a Value,
    ) -> std::pin::Pin<
        Box<dyn std::future::Future<Output = Result<ToolInvocationResult, RuntimeError>> + Send + 'a>,
    > {{
        todo!("EPIC 7.1: execute the tool identified by tool_id")
    }}

    fn llm_backend_for(&self, _backend: &str) -> Result<Arc<dyn DynLlmBackend>, RuntimeError> {{
        todo!("EPIC 7.1: resolve the named LLM backend")
    }}
}}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {{
    let module = Arc::new(from_canonical_bytes(TAU_IR)?);
    let entry = module.workflow.agents.keys().next().expect("IR module has at least one agent").clone();
    let outcome = run_ir(module, &entry, Arc::new(StubDispatcher), Vec::new()).await?;
    println!("{{outcome:?}}");
    Ok(())
}}
"#,
            lib = input.lib_crate_name,
        ),
    );

    out.insert(PathBuf::from("embed-rust/tau.wit"), input.wit.to_string());

    out.insert(
        PathBuf::from("embed-rust/README.md"),
        format!(
            "# {name} (rust host scaffold)\n\n\
             Generated by `tau embed --host rust` (EPIC 5.2). Baked IR hash: \
             `{hash}`.\n\n\
             Native host for the sibling rust-lib crate (`{lib}`). Link it, fill \
             in `StubDispatcher`'s `todo!()` port bodies (tool execution + LLM \
             backend — EPIC 7.1), and `cargo run`. The capabilities your \
             dispatcher must service are the WIT imports in `tau.wit`.\n",
            name = input.crate_name,
            hash = input.ir_hash,
            lib = input.lib_crate_name,
        ),
    );

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn render_embed_rust_emits_host_crate_that_drives_run_ir() {
        let out = render_embed_rust(EmbedRustInput {
            crate_name: "trivial_host",
            lib_crate_name: "trivial",
            ir_hash: "abc123",
            wit:
                "package tau:generated@0.1.0;\nworld runner {\n    import tau:host/host@0.1.0;\n}\n",
            tau_version: "0.0.0",
        });

        for f in ["Cargo.toml", "src/main.rs", "tau.wit", "README.md"] {
            assert!(
                out.contains_key(&PathBuf::from(format!("embed-rust/{f}"))),
                "missing embed-rust/{f}"
            );
        }

        let main = &out[&PathBuf::from("embed-rust/src/main.rs")];
        // Links the 5.1 rust-lib crate and drives run_ir with a stub dispatcher.
        assert!(main.contains("use trivial::{run_ir, TAU_IR}"), "{main}");
        assert!(
            main.contains("impl ToolDispatcher for StubDispatcher"),
            "{main}"
        );
        assert!(
            main.contains("todo!("),
            "port bodies must be todo!() stubs: {main}"
        );
        assert!(main.contains("run_ir("), "{main}");

        let cargo = &out[&PathBuf::from("embed-rust/Cargo.toml")];
        assert!(cargo.contains(r#"trivial = { path = ".." }"#), "{cargo}");
        assert!(
            cargo.contains(r#"tau-runtime-core = { version = "0.0.0""#),
            "{cargo}"
        );

        assert_eq!(
            out[&PathBuf::from("embed-rust/tau.wit")],
            "package tau:generated@0.1.0;\nworld runner {\n    import tau:host/host@0.1.0;\n}\n"
        );
        assert!(out[&PathBuf::from("embed-rust/README.md")].contains("abc123"));
    }
}
