//! `emit_rust_lib` — render the Variant B no_std embedding crate (EPIC 5.1).
//!
//! Bakes the canonical IR bytes + cap-derived WIT that the wasm-guest path
//! produces into a linkable Rust source crate. The product links this crate,
//! supplies port impls, and drives `tau_runtime_core::run_ir` (EPIC 7.1).

use std::collections::BTreeMap;
use std::path::PathBuf;

/// Inputs for [`render_rust_lib`].
pub struct RustLibInput<'a> {
    /// Sanitized project stem used as the crate name.
    pub crate_name: &'a str,
    /// Canonical IR bytes (from `lower_to_wasm_ir`).
    pub ir_bytes: &'a [u8],
    /// Lowercase-hex IR module hash.
    pub ir_hash: &'a str,
    /// Cap-derived WIT world text (from `world_from_module`).
    pub wit: &'a str,
    /// Pinned `tau-runtime-core` dependency version.
    pub tau_version: &'a str,
}

/// Render the rust-lib scaffold as crate-relative-path -> contents.
///
/// Returned keys: `Cargo.toml`, `src/lib.rs`, `tau.wit`, `README.md`. The
/// crate is *source* (never compiled here): a product links it, implements the
/// ports for the capabilities in `tau.wit`, and calls `run_ir(TAU_IR, …)`.
pub fn render_rust_lib(input: RustLibInput) -> BTreeMap<PathBuf, String> {
    let mut out = BTreeMap::new();

    let ir_literal = input
        .ir_bytes
        .iter()
        .map(|b| format!("{b}u8"))
        .collect::<Vec<_>>()
        .join(", ");

    out.insert(
        PathBuf::from("Cargo.toml"),
        format!(
            r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"
publish = false

# Generated by `tau build --target rust-lib` (EPIC 5.1). This is a no_std
# embedding scaffold: the product links it and supplies port impls (EPIC 7.1).
[dependencies]
tau-runtime-core = {{ version = "{ver}", default-features = false }}
"#,
            name = input.crate_name,
            ver = input.tau_version,
        ),
    );

    out.insert(
        PathBuf::from("src/lib.rs"),
        format!(
            r#"#![no_std]
//! Generated by `tau build --target rust-lib` (EPIC 5.1) — do not edit.
//!
//! Baked workflow IR + the runtime-core entrypoint. Link this crate from your
//! product, supply port impls, and drive [`run_ir`] with [`TAU_IR`].

/// Canonical IR bytes for this workflow.
pub const TAU_IR: &[u8] = &[{ir_literal}];

/// Lowercase-hex hash of the IR module (matches the `.tau`/wasm build).
pub const TAU_IR_HASH: &str = "{hash}";

pub use tau_runtime_core::run_ir;
"#,
            ir_literal = ir_literal,
            hash = input.ir_hash,
        ),
    );

    out.insert(PathBuf::from("tau.wit"), input.wit.to_string());

    out.insert(
        PathBuf::from("README.md"),
        format!(
            "# {name} (rust-lib embedding scaffold)\n\n\
             Generated by `tau build --target rust-lib`. Baked IR hash: `{hash}`.\n\n\
             Link this crate, implement the ports for the capabilities in `tau.wit`, \
             and call `run_ir(TAU_IR, …)`. See EPIC 7.1 for the full embedding API.\n",
            name = input.crate_name,
            hash = input.ir_hash,
        ),
    );

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn render_rust_lib_emits_expected_files_and_bakes_ir() {
        let ir = [0xDEu8, 0xAD, 0xBE, 0xEF];
        let out = render_rust_lib(RustLibInput {
            crate_name: "trivial",
            ir_bytes: &ir,
            ir_hash: "abc123",
            wit: "package tau:workflow;\nworld guest {}\n",
            tau_version: "0.0.0",
        });

        // File set present.
        for f in ["Cargo.toml", "src/lib.rs", "tau.wit", "README.md"] {
            assert!(out.contains_key(&PathBuf::from(f)), "missing {f}");
        }

        let lib = &out[&PathBuf::from("src/lib.rs")];
        assert!(lib.contains("#![no_std]"), "lib must be no_std");
        // IR bytes baked as a const, byte-for-byte.
        assert!(
            lib.contains("pub const TAU_IR: &[u8] = &[222u8, 173u8, 190u8, 239u8]"),
            "IR const not baked: {lib}"
        );
        assert!(lib.contains(r#"pub const TAU_IR_HASH: &str = "abc123""#));
        assert!(lib.contains("pub use tau_runtime_core::run_ir"));

        let cargo = &out[&PathBuf::from("Cargo.toml")];
        assert!(cargo.contains(r#"name = "trivial""#));
        assert!(cargo.contains(r#"tau-runtime-core = { version = "0.0.0""#));

        assert_eq!(
            out[&PathBuf::from("tau.wit")],
            "package tau:workflow;\nworld guest {}\n"
        );
    }
}
