//! Emit the Python `tau_sdk` authoring package.
//!
//! Output is stdlib-only (dataclasses/typing): typed builders plus a
//! deterministic `render_project`/`print_toml` that walks authored objects in
//! `SURFACE` order and prints `tau.toml`.

use std::collections::BTreeMap;
use std::path::PathBuf;

use crate::schema::SchemaModel;

/// Render the Python package as relative-path -> file-contents.
pub fn render_package(_schema: &SchemaModel) -> BTreeMap<PathBuf, String> {
    let mut out = BTreeMap::new();

    out.insert(
        PathBuf::from("pyproject.toml"),
        r#"[project]
name = "tau-sdk"
version = "0.0.0"
description = "Typed Python authoring SDK for tau agents"
requires-python = ">=3.9"

[tool.setuptools.packages.find]
where = ["."]
"#
        .to_string(),
    );

    out.insert(
        PathBuf::from("tau_sdk/__init__.py"),
        "from .factories import agent, tool, models, model, render_project, print_toml\n\n\
         __all__ = [\"agent\", \"tool\", \"models\", \"model\", \"render_project\", \"print_toml\"]\n"
            .to_string(),
    );

    out.insert(
        PathBuf::from("tau_sdk/factories.py"),
        FACTORIES_PY.to_string(),
    );
    out
}

/// The hand-tuned factories module. Fields mirror `authoring::SURFACE`; the
/// TOML renderer emits tables in SURFACE order. Kept as a literal because the
/// authoring surface is small and the byte-equal test pins its correctness.
const FACTORIES_PY: &str = r#"# GENERATED by tau-sdk-codegen. Do not edit by hand.
"""Typed authoring builders for tau agents (stdlib only)."""
from dataclasses import dataclass
from typing import Optional


@dataclass
class Model:
    backend: str
    model: str


@dataclass
class ToolConfig:
    native: str
    description: Optional[str] = None


@dataclass
class AgentConfig:
    display_name: str
    package: str
    model: str


def model(*, backend: str, model: str) -> Model:
    return Model(backend=backend, model=model)


def models(**aliases: Model) -> dict:
    return dict(aliases)


def tool(*, native: str, description: Optional[str] = None) -> ToolConfig:
    return ToolConfig(native=native, description=description)


def agent(*, display_name: str, package: str, model: str) -> AgentConfig:
    return AgentConfig(display_name=display_name, package=package, model=model)


def _toml_str(value: str) -> str:
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def render_project(project: str = "project", models: Optional[dict] = None, agents: Optional[dict] = None) -> str:
    models = models or {}
    agents = agents or {}
    # `packages` must declare every model backend (ProjectConfig validation);
    # it is authoring-only and dropped during lowering, so its exact contents
    # do not affect the canonical IR — only that validation passes.
    backends = sorted({m.backend for m in models.values()})
    lines = []
    lines.append("packages = [" + ", ".join(_toml_str(b) for b in backends) + "]")
    lines.append("")
    lines.append("[project]")
    lines.append("name = " + _toml_str(project))
    lines.append("")
    for alias, m in models.items():
        lines.append("[models." + alias + "]")
        lines.append("backend = " + _toml_str(m.backend))
        lines.append("model = " + _toml_str(m.model))
        lines.append("")
    for aid, a in agents.items():
        lines.append("[agents." + aid + "]")
        lines.append("display_name = " + _toml_str(a.display_name))
        lines.append("package = " + _toml_str(a.package))
        lines.append("model = " + _toml_str(a.model))
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def print_toml(project: str = "project", models: Optional[dict] = None, agents: Optional[dict] = None) -> None:
    import sys
    sys.stdout.write(render_project(project=project, models=models, agents=agents))
"#;
