//! Emit the Python `tau_sdk` authoring package.
//!
//! Output is stdlib-only (dataclasses/typing): typed builders plus a
//! deterministic `render_project`/`print_toml` that walks authored objects in
//! `SURFACE` order and prints `tau.toml`.

use std::collections::BTreeMap;
use std::path::PathBuf;

use crate::schema::SchemaModel;

/// Render the Python package as relative-path -> file-contents.
pub fn render_package(_schema: &SchemaModel) -> BTreeMap<PathBuf, String> {
    let mut out = BTreeMap::new();

    out.insert(
        PathBuf::from("pyproject.toml"),
        r#"[project]
name = "tau-sdk"
version = "0.0.0"
description = "Typed Python authoring SDK for tau agents"
requires-python = ">=3.9"

[tool.setuptools.packages.find]
where = ["."]
"#
        .to_string(),
    );

    out.insert(
        PathBuf::from("tau_sdk/__init__.py"),
        "from .factories import agent, models, model, tool, render_project, print_toml\n\n\
         __all__ = [\"agent\", \"models\", \"model\", \"tool\", \"render_project\", \"print_toml\"]\n"
            .to_string(),
    );

    out.insert(
        PathBuf::from("tau_sdk/factories.py"),
        FACTORIES_PY.to_string(),
    );
    out
}

/// The hand-tuned factories module. Fields mirror `authoring::SURFACE`; the
/// TOML renderer emits tables in SURFACE order. Kept as a literal because the
/// authoring surface is small and the byte-equal test pins its correctness.
const FACTORIES_PY: &str = r#"# GENERATED by tau-sdk-codegen. Do not edit by hand.
"""Typed authoring builders for tau agents (stdlib only)."""
from dataclasses import dataclass
from typing import Optional


@dataclass
class Model:
    backend: str
    model: str


@dataclass
class AgentConfig:
    display_name: str
    package: str
    model: str
    prompt: Optional[dict] = None
    tool_refs: Optional[list] = None


@dataclass
class ToolConfig:
    native: str
    description: str = ""
    capabilities: Optional[list] = None


def model(*, backend: str, model: str) -> Model:
    return Model(backend=backend, model=model)


def models(**aliases: Model) -> dict:
    return dict(aliases)


def tool(*, native: str, description: str = "", capabilities: Optional[list] = None) -> ToolConfig:
    return ToolConfig(native=native, description=description, capabilities=capabilities or [])


def agent(*, display_name: str, package: str, model: str, prompt: Optional[dict] = None, tool_refs: Optional[list] = None) -> AgentConfig:
    return AgentConfig(display_name=display_name, package=package, model=model, prompt=prompt, tool_refs=tool_refs)


def _toml_str(value: str) -> str:
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def _toml_inline(value) -> str:
    # Render a scalar / list / dict as a TOML inline value. Used for tool
    # `capabilities` (a list of `{ kind, paths }` inline tables). `bool` is
    # checked before `int` because `bool` is a subclass of `int` in Python.
    if isinstance(value, str):
        return _toml_str(value)
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(_toml_inline(v) for v in value) + "]"
    if isinstance(value, dict):
        return "{ " + ", ".join(k + " = " + _toml_inline(v) for k, v in value.items()) + " }"
    raise TypeError("unsupported TOML inline value: " + repr(value))


def render_project(project: str = "project", models: Optional[dict] = None, agents: Optional[dict] = None, tools: Optional[dict] = None) -> str:
    models = models or {}
    agents = agents or {}
    tools = tools or {}
    # `packages` must declare every model backend (ProjectConfig validation);
    # it is authoring-only and dropped during lowering, so its exact contents
    # do not affect the canonical IR — only that validation passes.
    backends = sorted({m.backend for m in models.values()})
    lines = []
    lines.append("packages = [" + ", ".join(_toml_str(b) for b in backends) + "]")
    lines.append("")
    lines.append("[project]")
    lines.append("name = " + _toml_str(project))
    lines.append("")
    for alias, m in models.items():
        lines.append("[models." + alias + "]")
        lines.append("backend = " + _toml_str(m.backend))
        lines.append("model = " + _toml_str(m.model))
        lines.append("")
    for tname, t in tools.items():
        lines.append("[tools." + tname + "]")
        lines.append("native = " + _toml_str(t.native))
        if t.description:
            lines.append("description = " + _toml_str(t.description))
        if t.capabilities:
            lines.append("capabilities = [" + ", ".join(_toml_inline(c) for c in t.capabilities) + "]")
        lines.append("")
    for aid, a in agents.items():
        lines.append("[agents." + aid + "]")
        lines.append("display_name = " + _toml_str(a.display_name))
        lines.append("package = " + _toml_str(a.package))
        lines.append("model = " + _toml_str(a.model))
        if a.tool_refs:
            lines.append("tool_refs = [" + ", ".join(_toml_str(r) for r in a.tool_refs) + "]")
        lines.append("")
        # A prompt is a sub-table, so it must follow every top-level key of
        # `[agents.<id>]` above.
        if a.prompt and "system" in a.prompt:
            lines.append("[agents." + aid + ".prompt]")
            lines.append("system = " + _toml_str(a.prompt["system"]))
            lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def print_toml(project: str = "project", models: Optional[dict] = None, agents: Optional[dict] = None, tools: Optional[dict] = None) -> None:
    import sys
    sys.stdout.write(render_project(project=project, models=models, agents=agents, tools=tools))
"#;
