//! Emit the `@tau/sdk` TypeScript authoring package. Factory names + fields
//! match `tau-ts-extract`'s recognized surface so authored `project.ts`
//! extracts unchanged. Import source must be exactly `"tau"`.

use std::collections::BTreeMap;
use std::path::PathBuf;

use crate::schema::SchemaModel;

/// Render the TS package as relative-path -> file-contents.
pub fn render_package(_schema: &SchemaModel) -> BTreeMap<PathBuf, String> {
    let mut out = BTreeMap::new();

    out.insert(
        PathBuf::from("package.json"),
        r#"{
  "name": "@tau/sdk",
  "version": "0.0.0",
  "description": "Typed TypeScript authoring SDK for tau agents",
  "types": "src/factories.ts",
  "main": "src/factories.ts"
}
"#
        .to_string(),
    );

    out.insert(
        PathBuf::from("tsconfig.json"),
        r#"{
  "compilerOptions": {
    "strict": true,
    "target": "ES2020",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "declaration": true
  }
}
"#
        .to_string(),
    );

    out.insert(PathBuf::from("src/factories.ts"), FACTORIES_TS.to_string());
    out
}

const FACTORIES_TS: &str = r#"// GENERATED by tau-sdk-codegen. Do not edit by hand.
export interface Model { backend: string; model: string }
export interface ToolConfig { native: string; description?: string }
export interface AgentConfig { display_name: string; package: string; model: string }

export const models = (m: Record<string, Model>): Record<string, Model> => m;
export const tool = (c: ToolConfig): ToolConfig => c;
export const agent = (c: AgentConfig): AgentConfig => c;
"#;
