# GENERATED by `tau export --harness py` — DO NOT EDIT.
# (VISION FIXTURE — target state, not yet generatable.)
# tau:gen harness-card=sha256:9f3ac2d15e08 — regenerate when the pin moves.
#
# The declension: a typed host scaffold derived from the harness card.
# The team implements EXACTLY the declared obligations (HostTools) and an
# approval callback — the loop, journal, budgets, capability enforcement,
# and card stay tau's, on the other side of the serve v2 socket. There is
# no tau runtime in this process (invariant 6).

from . import types


class HostTools:
    """One abstract method per declared [[harness.host_tool]]."""

    def metrics_query(self, req: types.MetricsQueryIn) -> types.MetricsQueryOut:
        raise NotImplementedError

    def pager_ack(self, req: types.PagerAckIn) -> types.PagerAckOut:
        raise NotImplementedError

    def runbook_apply(self, req: types.RunbookApplyIn) -> types.RunbookApplyOut:
        raise NotImplementedError


class Harness:
    """Connection to the tau engine (serve v2, unix socket, JSON-RPC).

    connect() verifies obligations UP FRONT: a host missing a declared
    tool is refused here, with the gap named — never at step 7
    (invariant 8; transcript 02-refusal.txt).
    """

    @classmethod
    def connect(cls, *, tools: HostTools, on_approval) -> "Harness": ...

    def session(self, pipeline: str) -> "Session": ...


class Session:
    """One run of an exposed pipeline. Iterating yields typed run events;
    host-tool steps arrive as reverse dispatch onto HostTools; the
    apply-fix elicitation suspends the run until on_approval returns a
    typed decision."""

    def run(self, input): ...
