# GENERATED by `tau export --harness py` — DO NOT EDIT.
# (VISION FIXTURE — target state.) Types are projected from the host-tool
# schemas + exposed pipelines' I/O + the elicitation resume_schema.

from dataclasses import dataclass


# ── exposed pipeline I/O ──────────────────────────────────────────────
@dataclass
class AlertRef:
    id: str


@dataclass
class Findings:
    cause: str
    evidence: list[dict]
    confidence: str


# ── host-tool contracts (schemas/host/*.json) ─────────────────────────
@dataclass
class MetricsQueryIn:
    query: str
    range: str


@dataclass
class MetricsQueryOut:
    series: list[dict]


@dataclass
class PagerAckIn:
    incident_id: str


@dataclass
class PagerAckOut:
    acked: bool


@dataclass
class RunbookApplyIn:
    plan: dict


@dataclass
class RunbookApplyOut:
    status: str
    log: str = ""


# ── approvals (resume_schema of runbook-exec/apply-fix) ───────────────
@dataclass
class ApplyFixElicitation:
    plan: dict
    rationale: str


@dataclass
class ApplyFixDecision:
    approved: bool
    note: str = ""
