from __future__ import annotations

from typing import Protocol

from app.domain.models import Task


class TaskRepository(Protocol):
    async def create(self, title: str, description: str = "") -> Task: ...
    async def get_by_id(self, task_id: int) -> Task | None: ...
    async def list_all(self, *, done: bool | None = None) -> list[Task]: ...
    async def update(self, task_id: int, **fields: object) -> Task | None: ...
    async def delete(self, task_id: int) -> bool: ...


class HealthChecker(Protocol):
    async def is_db_up(self) -> bool: ...
