# GENERATED by tau-sdk-codegen. Do not edit by hand.
"""Typed authoring builders for tau agents (stdlib only)."""
from dataclasses import dataclass
from typing import Optional


@dataclass
class Model:
    backend: str
    model: str


@dataclass
class AgentConfig:
    display_name: str
    package: str
    model: str


def model(*, backend: str, model: str) -> Model:
    return Model(backend=backend, model=model)


def models(**aliases: Model) -> dict:
    return dict(aliases)


def agent(*, display_name: str, package: str, model: str) -> AgentConfig:
    return AgentConfig(display_name=display_name, package=package, model=model)


def _toml_str(value: str) -> str:
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def render_project(project: str = "project", models: Optional[dict] = None, agents: Optional[dict] = None) -> str:
    models = models or {}
    agents = agents or {}
    # `packages` must declare every model backend (ProjectConfig validation);
    # it is authoring-only and dropped during lowering, so its exact contents
    # do not affect the canonical IR — only that validation passes.
    backends = sorted({m.backend for m in models.values()})
    lines = []
    lines.append("packages = [" + ", ".join(_toml_str(b) for b in backends) + "]")
    lines.append("")
    lines.append("[project]")
    lines.append("name = " + _toml_str(project))
    lines.append("")
    for alias, m in models.items():
        lines.append("[models." + alias + "]")
        lines.append("backend = " + _toml_str(m.backend))
        lines.append("model = " + _toml_str(m.model))
        lines.append("")
    for aid, a in agents.items():
        lines.append("[agents." + aid + "]")
        lines.append("display_name = " + _toml_str(a.display_name))
        lines.append("package = " + _toml_str(a.package))
        lines.append("model = " + _toml_str(a.model))
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def print_toml(project: str = "project", models: Optional[dict] = None, agents: Optional[dict] = None) -> None:
    import sys
    sys.stdout.write(render_project(project=project, models=models, agents=agents))
