//! tau-runtime host-shell error types.
//!
//! Re-exports the kernel's [`tau_runtime_core::error`] symbols and adds
//! host-shell-only variants via [`RuntimeError`] — a thin wrapper enum
//! that lifts core errors transparently (via `#[from] CoreRuntimeError`)
//! and tacks on the `std::io::Error`- and
//! `std::process::ExitStatus`-carrying variants that are incompatible
//! with `no_std`.
//!
//! The error taxonomy splits into two layers:
//!
//! - [`BuildError`] — failures during `RuntimeBuilder::build()`. The
//!   runtime never gets constructed.
//! - [`RuntimeError`] — operational failures during `Runtime::run`.
//!   Agent-level failures (capability denied, max turns reached) flow
//!   through `Ok(RunOutcome::Failed { status: AgentStatus::Failed{..}
//!   })` instead. See ADR-0006 for the dichotomy.
//!
//! [`CapabilityDenial`] is a helper type embedded as the `detail`
//! string of `AgentStatus::Failed { kind: PolicyDenied }` when
//! capability enforcement rejects a tool call. It is NOT a variant
//! of `RuntimeError`.

pub use tau_runtime_core::error::{
    BuildError, CapabilityDenial, HandshakeFailureReason, PluginKind,
    RuntimeError as CoreRuntimeError,
};

use thiserror::Error;

/// Host-shell `RuntimeError`.
///
/// Wraps the executor-agnostic [`CoreRuntimeError`] (all variants
/// except the tokio/std-only ones) and adds the host-shell-specific
/// variants that carry `std::io::Error`,
/// `std::process::ExitStatus`, or crate-internal types.
///
/// The [`From<CoreRuntimeError>`] impl (generated by `#[from]`) means
/// `?` propagation from code returning `CoreRuntimeError` works
/// transparently — the result is wrapped in `RuntimeError::Core(...)`.
#[derive(Error, Debug)]
#[non_exhaustive]
pub enum RuntimeError {
    /// Core (executor-agnostic) error.
    #[error(transparent)]
    Core(#[from] CoreRuntimeError),

    /// `tokio::process::Command::spawn` failed for the plugin binary
    /// (binary missing, not executable, sandbox policy denied, etc.).
    #[error("failed to spawn plugin {plugin}: {source}")]
    PluginSpawnFailed {
        /// The plugin name (from `LockedPlugin::manifest.name`).
        plugin: String,
        /// The underlying `std::io::Error` from `spawn`.
        #[source]
        source: std::io::Error,
    },

    /// Plugin process exited unexpectedly during a request. The
    /// captured `stderr_tail` (last N bytes of stderr) aids triage.
    #[error("plugin {plugin} crashed: exit {exit_status}")]
    PluginCrashed {
        /// The plugin name (from `LockedPlugin::manifest.name`).
        plugin: String,
        /// Exit status reported by the OS.
        exit_status: std::process::ExitStatus,
        /// Tail of the plugin's stderr, captured for diagnostics.
        stderr_tail: String,
    },

    /// Sandbox plan validation failed before plugin spawn.
    ///
    /// Raised by [`crate::plugin_host`] when
    /// [`crate::process_gate::validate_plan_against_adapter`] returns one or
    /// more errors (Layer 3 enforcement at spawn time).
    #[non_exhaustive]
    #[error("plugin {plugin}: sandbox validation failed:\n{}",
        errors.iter().map(|e| format!("  - {e}")).collect::<Vec<_>>().join("\n"))]
    SandboxValidationFailed {
        /// Plugin name (from `LockedPlugin::manifest.bin`).
        plugin: String,
        /// All validation errors collected in a single pass.
        errors: Vec<crate::process_gate::SandboxValidationError>,
    },

    /// Sandbox adapter failed to wrap the spawn command.
    ///
    /// Raised by [`crate::plugin_host`] when
    /// [`crate::process_gate::SandboxAdapter::wrap_spawn`] returns `Err`.
    #[non_exhaustive]
    #[error("plugin {plugin}: sandbox wrap-spawn failed: {source}")]
    SandboxWrapFailed {
        /// Plugin name (from `LockedPlugin::manifest.bin`).
        plugin: String,
        /// Underlying [`tau_ports::CapabilityError`].
        #[source]
        source: tau_ports::CapabilityError,
    },

    /// Resolving a declared credential through the chain failed.
    #[error("plugin {plugin}: credential {id} resolution failed: {reason}")]
    CredentialResolution {
        /// Plugin name (from `LockedPlugin::manifest.bin`).
        plugin: String,
        /// The logical credential id that failed to resolve.
        id: String,
        /// Human-readable failure reason.
        reason: String,
    },
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn plugin_kind_display() {
        assert_eq!(PluginKind::LlmBackend.to_string(), "llm-backend");
        assert_eq!(PluginKind::Tool.to_string(), "tool");
        assert_eq!(PluginKind::Storage.to_string(), "storage");
        assert_eq!(PluginKind::Sandbox.to_string(), "sandbox");
    }

    #[test]
    fn build_error_no_llm_backend_display() {
        let err = BuildError::NoLlmBackend;
        let s = format!("{err}");
        assert!(s.contains("no LLM backends registered"), "got: {s}");
    }

    #[test]
    fn build_error_name_collision_display() {
        let err = BuildError::NameCollision {
            kind: PluginKind::Tool,
            name: "echo".into(),
        };
        let s = format!("{err}");
        assert!(s.contains("name collision"), "got: {s}");
        assert!(s.contains("tool"), "got: {s}");
        assert!(s.contains("echo"), "got: {s}");
    }

    #[test]
    fn capability_denial_display_includes_all_fields() {
        let denial = CapabilityDenial::new(
            "agent-x",
            "pkg/y@1.0.0",
            "file_read",
            "filesystem.read",
            "/etc/passwd",
        );
        let s = format!("{denial}");
        assert!(s.contains("agent-x"), "got: {s}");
        assert!(s.contains("pkg/y@1.0.0"), "got: {s}");
        assert!(s.contains("filesystem.read"), "got: {s}");
        assert!(s.contains("/etc/passwd"), "got: {s}");
        assert!(s.contains("file_read"), "got: {s}");
    }

    use tau_ports::{LlmError, StorageError, ToolError};

    #[test]
    fn runtime_error_llm_backend_not_registered_display() {
        let err = RuntimeError::Core(CoreRuntimeError::LlmBackendNotRegistered {
            agent_id: "agent-1".into(),
            backend: "anthropic".into(),
        });
        let s = format!("{err}");
        assert!(s.contains("anthropic"), "got: {s}");
        assert!(s.contains("agent-1"), "got: {s}");
        assert!(s.contains("not registered"), "got: {s}");
    }

    #[test]
    fn runtime_error_tool_not_registered_display() {
        let err = RuntimeError::Core(CoreRuntimeError::ToolNotRegistered {
            tool_name: "ghost".into(),
            registered: vec!["echo".into(), "file_read".into()],
        });
        let s = format!("{err}");
        assert!(s.contains("ghost"), "got: {s}");
        assert!(s.contains("echo"), "got: {s}");
        assert!(s.contains("file_read"), "got: {s}");
    }

    #[test]
    fn build_error_tool_schema_invalid_display() {
        let err = BuildError::ToolSchemaInvalid {
            tool_name: "shell".into(),
            detail: "type 'objectt' is not valid".into(),
        };
        let s = format!("{err}");
        assert!(s.contains("shell"), "got: {s}");
        assert!(s.contains("input_schema"), "got: {s}");
        assert!(s.contains("Draft 7"), "got: {s}");
        assert!(s.contains("'objectt'"), "got: {s}");
    }

    #[test]
    fn runtime_error_plugin_contract_violation_display() {
        let err = RuntimeError::Core(CoreRuntimeError::PluginContractViolation {
            plugin: "anthropic".into(),
            detail: "expected JSON object, got array".into(),
        });
        let s = format!("{err}");
        assert!(s.contains("contract violation"), "got: {s}");
        assert!(s.contains("anthropic"), "got: {s}");
        assert!(s.contains("expected JSON object, got array"), "got: {s}");
    }

    #[test]
    fn runtime_error_plugin_spawn_failed_display() {
        let err = RuntimeError::PluginSpawnFailed {
            plugin: "echo-llm".into(),
            source: std::io::Error::new(std::io::ErrorKind::NotFound, "binary missing"),
        };
        let s = format!("{err}");
        assert!(s.contains("failed to spawn plugin"), "got: {s}");
        assert!(s.contains("echo-llm"), "got: {s}");
        assert!(s.contains("binary missing"), "got: {s}");
    }

    #[test]
    fn runtime_error_plugin_handshake_failed_display() {
        let err = RuntimeError::Core(CoreRuntimeError::PluginHandshakeFailed {
            plugin: "echo-llm".into(),
            reason: HandshakeFailureReason::Timeout,
        });
        let s = format!("{err}");
        assert!(s.contains("handshake failed"), "got: {s}");
        assert!(s.contains("echo-llm"), "got: {s}");
        assert!(s.contains("timeout"), "got: {s}");
    }

    #[test]
    fn runtime_error_plugin_crashed_display() {
        // Synthesize an `ExitStatus` via a quick child-process round-trip
        // so the test doesn't depend on platform-specific raw constructors.
        let exit_status = std::process::Command::new("true")
            .status()
            .or_else(|_| std::process::Command::new("/usr/bin/true").status())
            .expect("`true` must be available on the test host");
        let err = RuntimeError::PluginCrashed {
            plugin: "echo-llm".into(),
            exit_status,
            stderr_tail: "panicked at 'oops'".into(),
        };
        let s = format!("{err}");
        assert!(s.contains("crashed"), "got: {s}");
        assert!(s.contains("echo-llm"), "got: {s}");
    }

    #[test]
    fn handshake_failure_reason_timeout_display() {
        let r = HandshakeFailureReason::Timeout;
        assert_eq!(format!("{r}"), "timeout");
    }

    #[test]
    fn handshake_failure_reason_protocol_version_mismatch_display() {
        let r = HandshakeFailureReason::ProtocolVersionMismatch {
            host: "1".into(),
            plugin: "2".into(),
        };
        let s = format!("{r}");
        assert!(s.contains("protocol version mismatch"), "got: {s}");
        assert!(s.contains("1"), "got: {s}");
        assert!(s.contains("2"), "got: {s}");
    }

    #[test]
    fn handshake_failure_reason_provides_mismatch_display() {
        let r = HandshakeFailureReason::ProvidesMismatch {
            manifest: tau_domain::PortKind::LlmBackend,
            plugin_advertised: tau_domain::PortKind::Tool,
        };
        let s = format!("{r}");
        assert!(s.contains("provides mismatch"), "got: {s}");
        assert!(s.contains("llm_backend"), "got: {s}");
        assert!(s.contains("tool"), "got: {s}");
    }

    #[test]
    fn handshake_failure_reason_missing_required_method_display() {
        let r = HandshakeFailureReason::MissingRequiredMethod {
            method: "llm.complete".into(),
        };
        let s = format!("{r}");
        assert!(s.contains("missing required method"), "got: {s}");
        assert!(s.contains("llm.complete"), "got: {s}");
    }

    #[test]
    fn handshake_failure_reason_malformed_display() {
        let r = HandshakeFailureReason::Malformed {
            detail: "missing field `protocol_version`".into(),
        };
        let s = format!("{r}");
        assert!(s.contains("malformed response"), "got: {s}");
        assert!(s.contains("protocol_version"), "got: {s}");
    }

    #[test]
    fn runtime_error_composes_llm_via_from() {
        let llm_err = LlmError::Internal {
            message: "x".into(),
        };
        let runtime_err: RuntimeError = CoreRuntimeError::from(llm_err).into();
        assert!(matches!(
            runtime_err,
            RuntimeError::Core(CoreRuntimeError::Llm(LlmError::Internal { .. }))
        ));
    }

    #[test]
    fn runtime_error_composes_tool_via_from() {
        let tool_err = ToolError::Internal {
            message: "x".into(),
        };
        let runtime_err: RuntimeError = CoreRuntimeError::from(tool_err).into();
        assert!(matches!(
            runtime_err,
            RuntimeError::Core(CoreRuntimeError::Tool(ToolError::Internal { .. }))
        ));
    }

    #[test]
    fn runtime_error_composes_storage_via_from() {
        let storage_err = StorageError::Internal {
            message: "x".into(),
        };
        let runtime_err: RuntimeError = CoreRuntimeError::from(storage_err).into();
        assert!(matches!(
            runtime_err,
            RuntimeError::Core(CoreRuntimeError::Storage(StorageError::Internal { .. }))
        ));
    }

    #[test]
    fn runtime_error_composes_sandbox_via_from() {
        use tau_ports::CapabilityError;
        let sandbox_err = CapabilityError::Internal {
            message: "x".into(),
        };
        let runtime_err: RuntimeError = CoreRuntimeError::from(sandbox_err).into();
        assert!(matches!(
            runtime_err,
            RuntimeError::Core(CoreRuntimeError::Sandbox(CapabilityError::Internal { .. }))
        ));
    }

    #[test]
    fn runtime_error_internal_display() {
        let err = RuntimeError::Core(CoreRuntimeError::Internal {
            message: "unexpected".into(),
        });
        let s = format!("{err}");
        assert!(s.contains("internal"), "got: {s}");
        assert!(s.contains("unexpected"), "got: {s}");
    }

    #[test]
    fn capability_override_expands_displays_with_kind_and_reason() {
        let err = RuntimeError::Core(CoreRuntimeError::CapabilityOverrideExpands {
            kind: "fs.read".into(),
            reason: "/etc/** is not a subset".into(),
        });
        let msg = format!("{err}");
        assert!(msg.contains("fs.read"));
        assert!(msg.contains("not a subset"));
    }

    #[test]
    fn sandbox_validation_failed_display_includes_all_errors() {
        use crate::process_gate::SandboxValidationError;

        let plan_json = serde_json::json!({
            "kind": "fs.read",
            "paths": ["/tmp/x"]
        });
        let cap: tau_domain::Capability =
            serde_json::from_value(plan_json).expect("decode capability");

        let err = RuntimeError::SandboxValidationFailed {
            plugin: "foo".into(),
            errors: vec![
                SandboxValidationError::new("plug-1", cap.clone(), "shape A unsupported"),
                SandboxValidationError::new("plug-2", cap, "shape B unsupported"),
            ],
        };
        let rendered = format!("{err}");
        assert!(rendered.contains("shape A unsupported"), "got: {rendered}");
        assert!(rendered.contains("shape B unsupported"), "got: {rendered}");
        assert!(rendered.contains("plug-1"), "got: {rendered}");
        assert!(rendered.contains("plug-2"), "got: {rendered}");
    }
}
